"""D-QC-1 regression anchors: the quarterly clock must not move a single
bit of the annual era.

The fixture was generated by scripts/gen_qc_baseline.py from the
PRE-CHANGE code (see the qc-02-server branch history: the fixture commit
precedes every behavior change) and is never regenerated. If this file
fails, the quarterly release changed the meaning of a stored annual
session -- that is a defect in the release, never a reason to re-pin.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from ah.core.engine import run_path
from ah.core.numericworld import project_numeric
from ah.core.worldspec import WorldSpec
from ah.play import simulate_play

# `scripts/` is not an importable package in this repo's pytest layout
# (`ModuleNotFoundError: No module named 'scripts'` under `uv run pytest`,
# verified before writing this workaround; no existing test imports from
# `scripts/`). Per the plan (Task S1), the helpers are mirrored verbatim
# from scripts/gen_qc_baseline.py -- THAT script is the source of truth for
# both the digest method and the fixture; keep the two in sync by eye.

ROOT = Path(__file__).resolve().parents[1]
PRESETS = ROOT / "src" / "ah" / "presets"

#: The four live toy presets (the shipped decade worlds).
WORLDS = ("stagflation", "goldilocks", "deflation_bust", "reflation_boom")

#: A representative annual-era decision map: one of each action, plus a
#: commitment override at a year-close window, all on the annual grid.
ANNUAL_DECISIONS = {
    11: "derisk",
    23: {"action": "leanin", "commitments": {"pe": 5.0, "infra": 1.0}},
    35: "secondary",
    47: {"action": "commit", "commitments": {"pc": 0.0}},
    59: "hold",
}


def _paths(preset: str):
    doc = json.loads((PRESETS / f"{preset}.json").read_text(encoding="utf-8"))
    nw = project_numeric(WorldSpec.model_validate(doc))
    return run_path(nw, doc["engine_defaults"]["base_seed"])


def quarter_doc(q) -> dict:
    """Every numeric field a PlayQuarter carries (play.py:415-485), plus
    the per-sleeve maps.

    repr-float canonical JSON: any bit-level drift in any field changes
    the digest.
    """
    return {
        "quarter": q.quarter,
        "month": q.month,
        "cash": q.cash,
        "nav_true": q.nav_true,
        "nav_reported": q.nav_reported,
        "calls_paid": q.calls_paid,
        "distributions_received": q.distributions_received,
        "spending_paid": q.spending_paid,
        "forced_sale_total": q.forced_sale_total,
        "private_weight_true": q.private_weight_true,
        "private_weight_reported": q.private_weight_reported,
        "unfunded_total": q.unfunded_total,
        "drawdown_depth": q.drawdown_depth,
        "spread_ratio": q.spread_ratio,
        "f_dist": q.f_dist,
        "f_call": q.f_call,
        "new_commitments": q.new_commitments,
        "spending_basis": q.spending_basis,
        "spending_rate_annual": q.spending_rate_annual,
        "expired_undrawn": q.expired_undrawn,
        "terminal_distributions": q.terminal_distributions,
        "vintage_nav": dict(q.vintage_nav),
        "liquid_values": dict(q.liquid_values),
        "private_true": dict(q.private_true),
        "private_reported": dict(q.private_reported),
        "private_calls": dict(q.private_calls),
        "private_distributions": dict(q.private_distributions),
        "private_unfunded": dict(q.private_unfunded),
        "private_expired": dict(q.private_expired),
        "nav_true_months": list(q.nav_true_months),
        "nav_reported_months": list(q.nav_reported_months),
    }


def tape_digest(result) -> str:
    doc = {
        "quarters": [quarter_doc(q) for q in result.quarters],
        "final_value": result.final_value,
        "forced_sale_quarters": result.forced_sale_quarters,
        "total_forced_sales": result.total_forced_sales,
        "forced_secondaries": result.forced_secondaries,
    }
    blob = json.dumps(doc, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(blob.encode("ascii")).hexdigest()


FIXTURE = Path(__file__).parent / "fixtures" / "qc" / "annual-era-baseline.json"


@pytest.fixture(scope="module")
def baseline() -> dict:
    return json.loads(FIXTURE.read_text(encoding="ascii"))


@pytest.mark.parametrize("preset", WORLDS)
class TestAnnualEraIsBitIdentical:
    def test_flat_play_tape_is_bit_identical_to_the_annual_era_baseline(self, baseline, preset):
        paths = _paths(preset)
        assert tape_digest(simulate_play(paths, None)) == baseline[preset]["flat_play"]

    def test_flat_play_true_basis_is_bit_identical(self, baseline, preset):
        paths = _paths(preset)
        got = tape_digest(simulate_play(paths, None, use_reported=False))
        assert got == baseline[preset]["flat_play_true_basis"]

    def test_annual_decision_map_replays_bit_identically(self, baseline, preset):
        paths = _paths(preset)
        got = tape_digest(simulate_play(paths, ANNUAL_DECISIONS))
        assert got == baseline[preset]["annual_decisions"]
