/**
 * su-app-01 acceptance: the loader reproduces the server's seal recipe.
 *
 * The fixture bundle under test is generated by the repo's Python side
 * (`uv run ah bundle`) and committed at app/fixtures/ — the SAME artifact the
 * Python test suite verifies, so the two seal implementations are pinned to
 * each other through a shared byte stream, not through parallel re-derivation.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { webcrypto } from "node:crypto";
import { describe, expect, it } from "vitest";
import { BundleFormatError, parseBundle, sealTape } from "./bundle";

if (!globalThis.crypto?.subtle) {
  // happy-dom leaves WebCrypto off the global; Node's implementation is the same API
  Object.defineProperty(globalThis, "crypto", { value: webcrypto });
}

// vitest's cwd is the app root; happy-dom rewrites import.meta.url, so no URL math
const FIXTURE = resolve(process.cwd(), "fixtures", "toy.bundle.gz");

function fixtureBytes(): ArrayBuffer {
  const buf = readFileSync(FIXTURE);
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

describe("parseBundle", () => {
  it("loads the committed fixture and verifies its seal", async () => {
    const { bundle, sealVerified } = await parseBundle(fixtureBytes());
    expect(bundle.bundle_version).toBe("world-bundle-0.4");
    expect(sealVerified).toBe(true);
    expect(bundle.revealed.tape.length).toBe(bundle.meta.months);
    expect(bundle.summary.decision_months.length).toBeGreaterThan(0);
  });

  it("v0.4 carries the twin's ledger, aligned to quarter ends", async () => {
    const { bundle } = await parseBundle(fixtureBytes());
    const led = bundle.twin_ledger!;
    const n = led.quarter_months.length;
    expect(n).toBeGreaterThan(0);
    // quarters close on months 2, 5, 8, ... and stay inside the horizon
    led.quarter_months.forEach((m, i) => {
      expect(m).toBe(i * 3 + 2);
      expect(m).toBeLessThan(bundle.meta.months);
    });
    for (const series of [
      led.calls,
      led.distributions,
      led.nav_true,
      led.nav_reported,
      led.cash,
      led.unfunded,
      led.private_weight_true,
    ]) {
      expect(series.length).toBe(n);
    }
  });

  it("v0.2 carries the tier-1 wire, every item in-horizon (E2)", async () => {
    const { bundle } = await parseBundle(fixtureBytes());
    const artifacts = bundle.feed.artifacts ?? [];
    expect(artifacts.length).toBeGreaterThan(0);
    for (const a of artifacts) {
      expect(a.month).toBeGreaterThanOrEqual(0);
      expect(a.month).toBeLessThan(bundle.meta.months);
      expect(a.payload.dateline).toBeTruthy();
    }
    // in-timeline reveal: nothing on the wire is visible at month 0
    expect(artifacts.filter((a) => a.month < 0).length).toBe(0);
  });

  it("a doctored tape fails the seal, loudly", async () => {
    const { bundle } = await parseBundle(fixtureBytes());
    bundle.revealed.tape[0][0] += 0.000001;
    expect(await sealTape(bundle.revealed.tape)).not.toBe(bundle.revealed.tape_seal);
  });

  it("rejects an unsupported version", async () => {
    const { bundle } = await parseBundle(fixtureBytes());
    const doctored = { ...bundle, bundle_version: "world-bundle-9.9" };
    const bytes = new Blob([JSON.stringify(doctored)]).stream().pipeThrough(
      new CompressionStream("gzip"),
    );
    const gz = await new Response(bytes).arrayBuffer();
    await expect(parseBundle(gz)).rejects.toBeInstanceOf(BundleFormatError);
  });
});

describe("sealTape", () => {
  it("matches the Python recipe on a known tape", async () => {
    // sha256 over float64 LE bytes of [[1.5, -2.25], [0.125, 3.0]] row-major —
    // the SAME literal tape tests/test_live_mode.py seals with numpy, so the
    // two implementations are pinned to each other by value.
    const seal = await sealTape([
      [1.5, -2.25],
      [0.125, 3.0],
    ]);
    expect(seal).toBe(
      "sha256:7e327e9a0eb36f457386e18c60046f8a51ef4097be849fcfa1e387e90f57017b",
    );
  });
});
