"""WP5.7: generate RESEARCH-EVIDENCE.md from committed artifacts.

The consolidation is GENERATED, not hand-assembled (the WP2.10 discipline):
every number is read from a committed artifact or lock, and re-running this
script over the same tree yields byte-identical output. RQ map per the
kickoff row: RQ1 fidelity, RQ2 held-out regimes, RQ3 decision value, RQ5
commitment behaviour (harness only until players exist), RQ4 parked
(D-K5-2). Negative results are first-class sections, not footnotes.

Run:  uv run python scripts/build_research_evidence.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "src"))

OUT = _REPO_ROOT / "RESEARCH-EVIDENCE.md"

PITFALL = (
    "a policy that wins in the ensemble has been tested against the policy "
    "AND the generator together -- say so plainly."
)


def _lock(name: str) -> str:
    return json.loads((_REPO_ROOT / name).read_text("utf-8"))["digest"]


def _holdout_block() -> str:
    path = _REPO_ROOT / "artifacts/wp56/holdout-evaluation.json"
    h = json.loads(path.read_text("utf-8"))
    pr = h["primary_drawdown_surprise"]
    cov_rows = chr(10).join(
        f"| {f} | {c['months']} | {c['coverage_5_95']:.3f} |"
        for f, c in sorted(h["secondary_band_coverage_5_95"].items())
    )
    return f"""
  - **Primary (drawdown surprise): {pr["value"]:+.4f}** -- realized max
    drawdown {pr["realized_max_drawdown"]:.3f} (the 2022 bear) against the
    ensemble's p95 warning {pr["ensemble_p95_drawdown"]:.3f}. Reality stayed
    inside the warning: one sentence of support for decade-scale usability,
    with the single-realization caveat stated (n=1 decade; confirmation, not
    proof).
  - **Realized terminal wealth sits at the {h["secondary_terminal_wealth_percentile"]:.1%}
    percentile of the ensemble** -- the cone contained the downside and badly
    under-spanned the realized upside. Reported as a finding, no footnote.
  - **cpi band coverage 0.000**: the realized 2021-2023 inflation burst
    escaped the bands every month -- the C3-accepted inflation-era limitation
    (`Instructions/campaign2-regime-fix-options.md`) manifesting where its
    documentation predicted. cape_v's zero is partly definitional (holdout-
    span vs train+val demeaning centers). fx_usd went UNREAD (a reader
    fallback bug, logged in the artifact); per the sealed spec nothing
    re-runs -- the gap publishes as a gap.

| factor | realized months | coverage in [p5, p95] |
|---|---|---|
{cov_rows}
"""


def main() -> None:
    promo = json.loads(
        (_REPO_ROOT / "artifacts/campaign2/promotion-verdict.json").read_text("utf-8")
    )
    wff = json.loads((_REPO_ROOT / "artifacts/wp57/walkforward-final.json").read_text("utf-8"))
    density = json.loads((_REPO_ROOT / "artifacts/wp55/density-pilot.json").read_text("utf-8"))

    ds = wff["drawdown_surprise"]
    surprise_rows = "\n".join(
        f"| {k} | {v:+.4f} |" for k, v in sorted(ds["by_fold"].items(), key=lambda kv: int(kv[0]))
    )
    promo_rows = "\n".join(
        f"| {s['seed_index']} | {s['challenger_mean_elicitability']:.4f} | "
        f"{s['benchmark_mean_elicitability']:.4f} | {s['difference']:+.4f} | "
        f"{s['challenger_band_exceedance']} vs {s['benchmark_band_exceedance']} | yes |"
        for s in promo["per_seed"]
    )
    wilcoxon_rows = "\n".join(
        f"| {p} | {v['statistic']:.1f} | {v['p_value']:.4f} | {v['effect_size_rank_biserial']:+.3f} |"
        for p, v in wff["wilcoxon_vs_static_60_40"].items()
    )
    window_share = density["by_window"]
    first_two = window_share["0"]["share"] + window_share["1"]["share"]

    holdout_block = _holdout_block()
    doc = f"""# RESEARCH-EVIDENCE — the consolidated record (WP5.7)

*Generated by `scripts/build_research_evidence.py`; every number below is read
from a committed artifact, and re-running the script reproduces this file
byte-identically. Negative results are sections, not footnotes.*

**The seals this record is judged under:** `pre-registration.lock`
`{_lock("pre-registration.lock")}` · G3 `{_lock("pre-registration-g3.lock")}` ·
G5 `{_lock("pre-registration-g5.lock")}`.

**The standing caveat, verbatim at the top because it governs everything
below:** *{PITFALL}*

---

## RQ1 — Fidelity: does the generator reproduce the world's structure?

- **The sealed battery record** (`G2-EVIDENCE.md`, `ABLATION.md`,
  `ablation.json`): the hierarchical generator was selected by the sealed
  multi-seed rule over the bootstrap benchmark; the ablation grid's verdict is
  the committed record, generated not hand-assembled.
- **Campaign-2 promotion** (`artifacts/campaign2/PROMOTION.md`): the
  fifteen-factor generator (FX, CAPE, revived HY) beats `bootstrap-v1` in
  EVERY seed on both sealed clauses, both sides passing their batteries clean:

| seed | challenger elicit. | benchmark elicit. | d | band exceed. (C vs B) | beats |
|---|---|---|---|---|---|
{promo_rows}

- **Accepted limits, owner decision C3** (mechanism trace:
  `Instructions/campaign2-regime-fix-options.md`): level-factor half-lives
  revert at the block-reassembly timescale; equity/hml lost-decade excess
  (part start-state artifact). The 10yr tier claims NO pass (`G2-EVIDENCE.md`
  §5) and that honesty is carried here unchanged.

## RQ2 — Held-out regimes: does it generalize to data it never saw?

- **The severe test is INCONCLUSIVE, and that is the finding**
  (`artifacts/wp211/SEVERE-TEST.md`): excluding the 1970s and regenerating
  from the 1965 state moves the era-frequency gap by ~6-8% of a gap that
  exists with the decade in-sample. The reading is a recorded human
  judgement (S2-SEVERE-GATING); the L3 leg is structurally vacuous (0 blocks
  dropped) — stated in the evidence, not smoothed.
- **THE ONE-SHOT HOLDOUT IS SPENT** (owner authorization verbatim "Go",
  2026-08-03; spec sealed AM-2026-08-02-006; one generation at base_seed
  20260000, one token read, one table --
  `artifacts/wp56/holdout-evaluation.json`). The result, verbatim both ways:
{holdout_block}

## RQ3 — Decision value: do ensemble-informed decisions beat benchmarks?

- **The final walk-forward ran on the sealed protocol**
  (`artifacts/wp57/walkforward-final.json`; folds per AM-2026-08-02-005,
  five of six benchmark policies — `static_endowment_mix` is UNCOMPUTABLE,
  commodities unsourced, RFR-8). Wilcoxon vs `static_60_40` on terminal log
  wealth (effect sizes always, per the sealed rule):

| policy | statistic | p | rank-biserial |
|---|---|---|---|
{wilcoxon_rows}

- **The frozen primary — drawdown surprise — is NEGATIVE in all ten folds**
  (mean {ds["mean"]:+.4f}, worst {ds["max"]:+.4f}): realized drawdowns never
  exceeded the promoted generator's p95 warning. Read BOTH ways: the cone
  never under-warned, and it is loose against a calm realized decade
  (unconditional year-one cone vs 2011-2020). Model-level look-ahead stated:
  the generator trained on 1990-2020; a per-fold-retrained variant is named
  future work.

| fold | drawdown surprise |
|---|---|
{surprise_rows}

- **Decision-density pilot** (`artifacts/wp55/density-pilot.md`): across 300
  worlds, {first_two:.0%} of total |contribution| sits in the first two
  decision windows ("consequence concentrates at t0", supported at pilot
  scale) with a mid-decade bump above the time-decay line; the
  window-vs-regime confound of fixed preset schedules is stated, and the
  generated-world full run (budgeted from measured rates in the same report)
  is what breaks it.
- **The counterfactual machinery is exact** (`ah.gen.recone`,
  `ah.eval.counterfactual`): re-coning conditions every layer exactly (the
  wp5-03 verification record), and the was-it-a-good-call metric scores
  paired deltas on identical continuations.

## RQ5 — Commitment behaviour under pressure

**Harness only, by design, until players exist** (the kickoff's phrasing).
The pacing levers, forced-sale waterfall, policy twin (DN-5 v0.2) and the
tournament's cohort export are built and tested; behavioural claims await
consented human runs (DN-6's M4 consent clause is the blocking item, on the
counsel track).

## RQ4 — Practitioner robustness panel

**PARKED, owner decision D-K5-2** ("until the product is polished — and
wanted then"). Re-raised at the beta/M4 boundary; recruitment is not the
constraint.

---

## The negative results, collected

1. **G1's 2022 replay: FAIL** (`WP3.11`) — the honest answer to "does the
   engine reproduce 2022?" with the mark-lag limitation recorded.
2. **The severe test: INCONCLUSIVE** (RQ2 above) — reported as such.
3. **B' and A' both null** (`Instructions/campaign2-regime-fix-options.md`):
   guidance moves persistence the wrong way; the residual parameterization
   moves nothing — the diagnosis that followed relocated the defect and the
   chased anchors themselves.
4. **The 10yr tier claims no pass**; its two structural-gap regime metrics
   remain NaN-marked.
5. **`static_endowment_mix` and two D4 strategies are uncomputable**
   (commodities unsourced) — reported wherever they appear.

## Reproducibility appendix

- Every RunRecord regenerates its outputs from stored inputs
  (`ah.store.runrecords.verify_run`); `ah inspect RUN_ID` renders any run's
  figure page by REGENERATING it, digest-verified on every render.
- Every committed evidence artifact names its generating script; the
  ablation tables, promotion verdict, density pilot and walk-forward final
  are all script outputs.
- The three locks above hash the thresholds AND the judging code together;
  amendments are append-only (`governance/amendment-log.yaml`).

*Not investment advice.*
"""
    OUT.write_text(doc, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(doc.splitlines())} lines)")


if __name__ == "__main__":
    main()
