"""Campaign R1 Track B — compare the vintage re-run against the sealed record.

Pure functions only (the 3.5 h run lives in campaign_r1_generator.py). The
baseline is the committed ``artifacts/campaign2/promotion-verdict.json``; the
rerun summary is the same per-seed shape produced on the new vintage. Every
comparison anchors on the recorded NUMBERS and booleans, never on prose
(sealed-bands-not-prose-anchors).
"""

from __future__ import annotations

from typing import Any

#: per-seed fields compared, in report order
_FIELDS: tuple[tuple[str, str], ...] = (
    ("challenger_mean_elicitability", "hier-flow mean elicitability"),
    ("benchmark_mean_elicitability", "bootstrap mean elicitability"),
    ("difference", "difference (flow - bootstrap)"),
    ("challenger_band_exceedance", "hier-flow band exceedances"),
    ("benchmark_band_exceedance", "bootstrap band exceedances"),
)


def compare_cells(baseline: dict[str, Any], rerun: dict[str, Any]) -> list[dict[str, Any]]:
    """Per-seed, per-metric rows: recorded value, re-run value, delta."""
    base_by_seed = {r["seed_index"]: r for r in baseline["per_seed"]}
    rows: list[dict[str, Any]] = []
    for r in rerun["per_seed"]:
        k = r["seed_index"]
        if k not in base_by_seed:
            raise SystemExit(f"campaign R1: rerun seed {k} has no recorded baseline row")
        b = base_by_seed[k]
        for field, label in _FIELDS:
            old, new = float(b[field]), float(r[field])
            rows.append(
                {
                    "seed_index": k,
                    "metric": label,
                    "recorded": old,
                    "rerun": new,
                    "delta": new - old,
                }
            )
        rows.append(
            {
                "seed_index": k,
                "metric": "beats_this_seed (sealed clause I + II)",
                "recorded": bool(b["beats_this_seed"]),
                "rerun": bool(r["beats_this_seed"]),
                "delta": int(bool(r["beats_this_seed"])) - int(bool(b["beats_this_seed"])),
            }
        )
    return rows


def render_markdown(
    rows: list[dict[str, Any]],
    *,
    vintage: str,
    baseline_vintage: str,
    baseline_verdict: str,
    rerun_pooled: dict[str, Any],
    baseline_pooled: dict[str, Any],
) -> str:
    """The Track B report. Guard header is pinned by test — do not soften it."""
    lines = [
        "# Campaign R1 - Track B: the generator cells on the new vintage",
        "",
        f"*Generated by `scripts/campaign_r1_generator.py`: the six campaign-2 "
        f"cells (bootstrap-v1 and hier-flow-v1, three seeds each, EXISTING "
        f"checkpoints verified by hash) re-run against vintage `{vintage}`, "
        f"compared with the sealed record on `{baseline_vintage}`.*",
        "",
        "**This is an exhibit, not a gate.** It cannot re-judge promotion: the",
        "holdout was spent at WP5.6, and the sealed verdicts remain the",
        f"verdicts (recorded: `{baseline_verdict}`). The standing caveat on",
        "hier-flow-v1 carries forward unchanged - regime persistence",
        "undercalled, drawdowns understated ~2x, the decade tier structurally",
        "unavailable. What this CAN show is whether the promotion evidence is",
        "fragile to the data refresh: same checkpoints, same sealed",
        "arithmetic, new vintage. Any drift outside a sealed band below is a",
        "finding for the owner, not something this campaign fixes.",
        "",
        "## Per-seed comparison",
        "",
        "| seed | metric | recorded | re-run | delta |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        rec, new, delta = r["recorded"], r["rerun"], r["delta"]
        if isinstance(rec, bool):
            lines.append(f"| {r['seed_index']} | {r['metric']} | {rec} | {new} | {delta:+d} |")
        else:
            lines.append(
                f"| {r['seed_index']} | {r['metric']} | {rec:.6f} | {new:.6f} | {delta:+.6f} |"
            )
    lines += [
        "",
        "## Pooled (the sealed multi-seed rule's arithmetic, both vintages)",
        "",
        "| quantity | recorded | re-run |",
        "|---|---|---|",
        f"| mean_d | {float(baseline_pooled['mean_d']):.6f} "
        f"| {float(rerun_pooled['mean_d']):.6f} |",
        f"| sd_d (ddof=1) | {float(baseline_pooled['sd_d_ddof1']):.6f} "
        f"| {float(rerun_pooled['sd_d_ddof1']):.6f} |",
        f"| pooled_beat | {bool(baseline_pooled['pooled_beat'])} "
        f"| {bool(rerun_pooled['pooled_beat'])} |",
        "",
        "band status anchors: the per-seed band-exceedance counts above ARE",
        "the sealed clause-II quantities (booleans and counts from the judged",
        "JSON, never prose).",
        "",
    ]
    return "\n".join(lines)
