"""CMDTY verification: the AQR CFTLR intake and construction on real data.

Operational, not a test: reads the licensed workbook from gitignored
``data/aqr/`` (local, never committed), fetches the free cross-check series
(``fred.CMDTY_GLOBAL``, ``fred.CMDTY_PPI``) and the risk-free leg
(``french.rf``) live, builds the total-return series, and writes
``docs/data/CMDTY-REPORT.md``. Only derived statistics are committed; the
underlying AQR values never leave ``data/``.

Run:  uv run python scripts/cmdty_report.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "docs" / "data" / "CMDTY-REPORT.md"

EPISODES = (
    ("WW1 and aftermath (1915-20)", "1915-01", "1920-12"),
    ("1930-32 deflation", "1930-01", "1932-12"),
    ("1973-74 oil shock", "1973-01", "1974-12"),
    ("GFC (2008)", "2008-01", "2008-12"),
    ("2020-22 cycle", "2020-01", "2022-12"),
)


def _load_env() -> None:
    if os.environ.get("FRED_API_KEY"):
        return
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("FRED_API_KEY=") and "=" in line:
                os.environ["FRED_API_KEY"] = line.split("=", 1)[1].strip()


def main() -> int:
    _load_env()
    if not os.environ.get("FRED_API_KEY"):
        print("FRED_API_KEY not set (checked env and .env)")
        return 1

    import numpy as np
    import pandas as pd

    from ah.data import cmdty_close as cc
    from ah.data.connectors.aqr_cftlr import WORKBOOK_NAME, parse_workbook
    from ah.data.connectors.fred import FredConnector
    from ah.data.connectors.french import FrenchConnector
    from ah.data.manifest import load_requirements

    workbook = ROOT / "data" / "aqr" / WORKBOOK_NAME
    if not workbook.exists():
        print(f"missing {workbook} -- the owner-supplied workbook is not in place")
        return 1
    cols = parse_workbook(workbook)
    excess, spot = cols["ew_excess"], cols["ew_spot"]
    print(
        f"workbook: {len(excess)} months, "
        f"{excess['date'].min().date()}..{excess['date'].max().date()}"
    )

    reqs = load_requirements()
    fred, french = FredConnector(), FrenchConnector()

    def _fetch(conn, sid: str) -> pd.DataFrame:
        req = reqs[sid]
        frame = conn.parse(conn.fetch(req), req)
        print(f"{sid}: {len(frame)} obs")
        return frame

    rf = _fetch(french, "french.rf")
    cmdty_global = _fetch(fred, "fred.CMDTY_GLOBAL")
    cmdty_ppi = _fetch(fred, "fred.CMDTY_PPI")

    tr = cc.total_return(excess, rf)
    chk_global = cc.cross_check(spot, cmdty_global)
    chk_ppi = cc.cross_check(spot, cmdty_ppi)

    series = tr.frame.set_index("date")["value"]
    ann = float(np.asarray(series.mean())) * 12
    vol = float(np.asarray(series.std(ddof=1))) * (12**0.5)

    def _episode(lo: str, hi: str) -> str:
        w = series.loc[lo:hi]
        if len(w) == 0:
            return "excess-only era (no risk-free leg): not in the TR frame"
        cum = float((1.0 + w).prod() - 1.0)
        return f"cumulative TR {cum:+.1%}, worst month {w.min():+.1%}"

    lines = [
        "# CMDTY — the commodities total-return construction, verified",
        "",
        "*Generated by `scripts/cmdty_report.py`. Source: the owner-supplied AQR",
        "CFTLR workbook in gitignored `data/aqr/` — only derived statistics appear",
        "here; raw values are never committed (owner ruling C2, REG licence).",
        f"Rule `{cc.RULE_ID}`. {cc.ATTRIBUTION}*",
        "",
        "## Coverage",
        "",
        f"- Source excess returns: {len(excess)} months, "
        f"{excess['date'].min().date()} .. {excess['date'].max().date()}.",
        f"- Total-return series (`aqr.cmdty_ew_tr` = excess + `french.rf`): "
        f"{len(tr.frame)} months, {tr.frame['date'].min().date()} .. "
        f"{tr.frame['date'].max().date()}.",
        f"- Excess-only pre-history (excluded from TR, never zero-filled): "
        f"{tr.excess_only[0]} .. {tr.excess_only[1]}."
        if tr.excess_only
        else "- No excess-only pre-history: the risk-free leg covers the source.",
        f"- Annualized TR mean {ann:+.2%}, vol {vol:.2%} — sanity magnitudes, not",
        "  performance claims.",
        "",
        "## Cross-checks against the registered free price indices",
        "",
        "| comparison | months | corr |",
        "|---|---|---|",
        f"| spot return vs fred.CMDTY_GLOBAL log-returns | {int(chk_global['n_obs'])} | {chk_global['corr']:.3f} |",
        f"| spot return vs fred.CMDTY_PPI log-returns | {int(chk_ppi['n_obs'])} | {chk_ppi['corr']:.3f} |",
        "",
        "- The indices are different baskets (IMF global; US PPI), so these are",
        "  co-movement checks against mis-parsing, not identity tests.",
        "",
        "## Episodes, as the series tells them",
        "",
    ]
    for name, lo, hi in EPISODES:
        lines.append(f"- **{name}**: {_episode(lo, hi)}")
    lines += [
        "",
        "## Standing posture",
        "",
        "- The sealed `commodities` factor is STILL `kind: unavailable` and still",
        "  in `missing_factors` — a test pins it. Closing it is the amendment",
        "  drafted in `governance/proposed/PROPOSED-AM-commodities-close.md`,",
        "  which is the owner's ratification: re-seal, factor registration, and",
        "  activation into FUTURE campaigns only.",
        "- Commercial clearance of the AQR terms is an OPEN registry item.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    print(
        f"tr: {len(tr.frame)}m; corr_global={chk_global['corr']:.3f} corr_ppi={chk_ppi['corr']:.3f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
