"""FSEXT verification: the CP-bill funding_spread extension on real data.

Operational, not a test (network + FRED_API_KEY): fetches the six legs
through the registered FRED connector, chains the CP and bill segments,
fits the TED level map on the 1986-2022 overlap, and writes
``docs/data/FSEXT-REPORT.md`` -- the overlap scrutiny that gates acceptance,
and the evidence the span amendment would cite. The vintage store is
untouched; a quarantined refresh stays quarantined.

Run:  uv run python scripts/fsext_overlap_report.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "docs" / "data" / "FSEXT-REPORT.md"

EPISODES = (
    ("1937-38 recession", "1937-01", "1938-12"),
    ("Penn Central (1970)", "1970-05", "1970-12"),
    ("Franklin National (1974)", "1974-05", "1974-12"),
    ("Volcker peak (1980-82)", "1980-01", "1982-12"),
    ("post-TED era (2022+)", "2022-02", "2026-12"),
)


def _load_env() -> None:
    if os.environ.get("FRED_API_KEY"):
        return
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("FRED_API_KEY=") and "=" in line:
                os.environ["FRED_API_KEY"] = line.split("=", 1)[1].strip()


def main() -> int:
    _load_env()
    if not os.environ.get("FRED_API_KEY"):
        print("FRED_API_KEY not set (checked env and .env)")
        return 1

    import pandas as pd

    from ah.data import funding_extend as fx
    from ah.data.connectors.fred import FredConnector
    from ah.data.manifest import load_requirements

    reqs = load_requirements()
    conn = FredConnector()
    frames: dict[str, pd.DataFrame] = {}
    for sid in (
        "fred.TEDRATE",
        "fred.CPF3M",
        "fred.CP3M",
        "fred.CP3M_NBER",
        "fred.TB3M_SEC",
        "fred.TB3MS",
    ):
        req = reqs[sid]
        frames[sid] = conn.parse(conn.fetch(req), req)
        print(
            f"{sid}: {len(frames[sid])} obs, "
            f"{frames[sid]['date'].min().date()}..{frames[sid]['date'].max().date()}"
        )

    segments: dict[str, dict[str, float]] = {}
    cp = fx.cp_series(frames["fred.CPF3M"], frames["fred.CP3M"], frames["fred.CP3M_NBER"], segments)
    bill = fx.bill_series(frames["fred.TB3M_SEC"], frames["fred.TB3MS"], segments)
    spread = (cp - bill.reindex(cp.index)).dropna()
    stats = fx.overlap_stats(frames["fred.TEDRATE"], spread)
    ext = fx.extend_funding_spread(
        frames["fred.TEDRATE"],
        frames["fred.CPF3M"],
        frames["fred.CP3M"],
        frames["fred.CP3M_NBER"],
        frames["fred.TB3M_SEC"],
        frames["fred.TB3MS"],
    )
    proxy = ext.frame.loc[ext.frame["is_proxy"]]
    back = proxy.loc[proxy["date"] < pd.Timestamp("1986-01-01")]
    fwd = proxy.loc[proxy["date"] > pd.Timestamp("2022-01-31")]

    series = ext.frame.set_index("date")["value"]

    def _episode(lo: str, hi: str) -> str:
        w = series.loc[lo:hi]
        if len(w) == 0:
            return "no data"
        return f"peak {w.max():.2f} ({w.idxmax().date()}), mean {w.mean():.2f}"

    lines = [
        "# FSEXT — funding_spread extended both ways on CP-bill, verified on real data",
        "",
        "*Generated by `scripts/fsext_overlap_report.py` (live FRED fetch; store",
        "untouched). Owner rulings F1-F3 in",
        "`docs/superpowers/specs/2026-08-09-fsext-scoping.md`; rule",
        f"`{fx.FUNDING_RULE.rule_id}`. Nothing consumes this series until the owner",
        "ratifies the span amendment.*",
        "",
        "## The TED fit (level map, 1986-01..2022-01 overlap)",
        "",
        "| quantity | value |",
        "|---|---|",
        f"| overlap months (n) | {int(stats['n_obs'])} |",
        f"| a (intercept, pct) | {stats['a']:.4f} |",
        f"| b (slope) | {stats['b']:.4f} |",
        f"| RMSE (pct points) | {stats['rmse']:.4f} |",
        f"| correlation | {stats['corr']:.4f} |",
        "",
        "## Segment joins (offset applied, residual RMSE, overlap months)",
        "",
        "| join | offset | rmse | n |",
        "|---|---|---|---|",
    ]
    for join, d in ext.segments.items():
        lines.append(
            f"| {join} | {d['offset']:+.3f} | {d['overlap_rmse']:.3f} | {int(d['n_overlap'])} |"
        )
    lines += [
        "",
        "## The extension",
        "",
        f"- Backward: **{len(back)}** proxy months "
        f"({back['date'].min().date()} .. {back['date'].max().date()}).",
        f"- Forward (the post-TED repair): **{len(fwd)}** proxy months "
        f"({fwd['date'].min().date()} .. {fwd['date'].max().date()}).",
        "- Observed TED months untouched (tested offline); every filled row is",
        f"  `is_proxy=True` under `{fx.FUNDING_RULE.rule_id}`.",
        "",
        "## Episodes, as the extended series tells them",
        "",
    ]
    for name, lo, hi in EPISODES:
        lines.append(f"- **{name}**: {_episode(lo, hi)}")
    lines += [
        "",
        "## Caveats, stated before anyone asks",
        "",
        "- TED is unsecured BANK funding; CP-bill is high-grade CORPORATE funding.",
        "  They co-move in shared stress but not identically (2008: TED ~4.6 while",
        "  CP spreads peaked lower and financial CP froze outright). Owner ruling",
        "  F1 accepts the recreation with this difference disclosed, not erased.",
        "- The CP leg changes instrument across segments (prime -> plain -> AA",
        "  financial); the join offsets and residuals above are the measurement of",
        "  that drift.",
        "- The 1934-01 floor is the bill leg's start (ruling F3); 1929-33 remains",
        "  out of reach without a weaker bill proxy, deliberately not attempted.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    print(
        f"fit: a={stats['a']:.4f} b={stats['b']:.4f} corr={stats['corr']:.4f} "
        f"rmse={stats['rmse']:.4f}; back={len(back)}m fwd={len(fwd)}m"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
