"""HQMEXT verification: the Aaa extension of the 10y HQM rate on real data.

Operational, not a test (network + FRED_API_KEY): fetches HQMCB10YR, AAA and
GS10 through the registered FRED connector, fits the level map on the 1984+
overlap, runs the H2 slope diagnostic over the pre-HQM era, and writes
``docs/data/HQMEXT-REPORT.md``. The vintage store is untouched.

Run:  uv run python scripts/hqmext_overlap_report.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "docs" / "data" / "HQMEXT-REPORT.md"

EPISODES = (
    ("1920-21 deflation", "1920-01", "1921-12"),
    ("1932 depression trough", "1932-01", "1932-12"),
    ("WW2 pegged era", "1942-01", "1945-12"),
    ("Volcker peak (1981)", "1981-01", "1982-12"),
)


def _load_env() -> None:
    if os.environ.get("FRED_API_KEY"):
        return
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("FRED_API_KEY=") and "=" in line:
                os.environ["FRED_API_KEY"] = line.split("=", 1)[1].strip()


def main() -> int:
    _load_env()
    if not os.environ.get("FRED_API_KEY"):
        print("FRED_API_KEY not set (checked env and .env)")
        return 1

    import pandas as pd

    from ah.data import hqm_extend as hx
    from ah.data.connectors.fred import FredConnector
    from ah.data.manifest import load_requirements

    reqs = load_requirements()
    conn = FredConnector()
    frames: dict[str, pd.DataFrame] = {}
    for sid in ("treasury.hqm_curve", "fred.AAA", "fred.GS10"):
        req = reqs[sid]
        frames[sid] = conn.parse(conn.fetch(req), req)
        print(
            f"{sid}: {len(frames[sid])} obs, "
            f"{frames[sid]['date'].min().date()}..{frames[sid]['date'].max().date()}"
        )

    stats = hx.overlap_stats(frames["treasury.hqm_curve"], frames["fred.AAA"])
    diag = hx.slope_diagnostic(
        frames["treasury.hqm_curve"], frames["fred.AAA"], frames["fred.GS10"]
    )
    ext = hx.extend_hqm(frames["treasury.hqm_curve"], frames["fred.AAA"])
    proxy = ext.frame.loc[ext.frame["is_proxy"]]
    series = ext.frame.set_index("date")["value"]

    def _episode(lo: str, hi: str) -> str:
        w = series.loc[lo:hi]
        if len(w) == 0:
            return "no data"
        return f"peak {w.max():.2f} ({w.idxmax().date()}), mean {w.mean():.2f}"

    worst = int(diag["divergence_worst_month"])
    lines = [
        "# HQMEXT — the 10y HQM rate extended to 1919 on Moody's Aaa, verified on real data",
        "",
        "*Generated by `scripts/hqmext_overlap_report.py` (live FRED fetch; store",
        "untouched). Owner rulings H1-H3 in",
        "`docs/superpowers/specs/2026-08-09-hqmext-decisions.md`; rule",
        f"`{hx.HQM_RULE.rule_id}`. Nothing consumes this series until the owner",
        "ratifies the span amendment.*",
        "",
        "## The fit (level map, 1984+ overlap)",
        "",
        "| quantity | value |",
        "|---|---|",
        f"| overlap months (n) | {int(stats['n_obs'])} |",
        f"| a (intercept, pct) | {stats['a']:.4f} |",
        f"| b (slope) | {stats['b']:.4f} |",
        f"| RMSE (pct points) | {stats['rmse']:.4f} |",
        f"| correlation | {stats['corr']:.4f} |",
        "",
        "## The H2 slope diagnostic (registered construction stays the simple fit)",
        "",
        f"- Term-slope coefficient on the overlap: {diag['slope_coef']:+.4f}; overlap",
        f"  RMSE {diag['overlap_rmse_simple']:.4f} simple vs {diag['overlap_rmse_slope']:.4f}",
        "  with the slope term.",
        f"- Extrapolated over {int(diag['n_pre_months_compared'])} pre-HQM months",
        f"  (1953+): mean divergence {diag['divergence_mean']:.3f} pct, max",
        f"  {diag['divergence_max']:.3f} pct at {worst // 100}-{worst % 100:02d}.",
        "- Per ruling H2 this is the revisit trigger, not a construction change:",
        "  if the divergence above reads as material where it matters, the owner",
        "  revisits before anything consumes the series.",
        "",
        "## The extension",
        "",
        f"- **{len(proxy)}** proxy months "
        f"({proxy['date'].min().date()} .. {proxy['date'].max().date()}), all",
        f"  `is_proxy=True` under `{hx.HQM_RULE.rule_id}`; observed months untouched",
        "  (tested offline). Pre-1934 months are panel-irrelevant until other",
        "  factors reach there (ruling H3).",
        "",
        "## Episodes, as the extended series tells them",
        "",
    ]
    for name, lo, hi in EPISODES:
        lines.append(f"- **{name}**: {_episode(lo, hi)}")
    lines += [
        "",
        "## Caveats, stated before anyone asks",
        "",
        "- Aaa is a seasoned ~20y+ Aaa-only portfolio yield; HQM 10y is a spot,",
        "  exactly-ten-year, A/AA/AAA blend. The level fit absorbs the average",
        "  difference; the time-varying maturity premium is what the diagnostic",
        "  above measures.",
        "- The span consequence: with VOLEXT, FSEXT and this extension verified,",
        "  the next binding factor is `ust_2y` (GS2, 1976-06), then `fx_usd`",
        "  (1973-01). The span draft's addendum tracks the chain.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    print(
        f"fit: a={stats['a']:.4f} b={stats['b']:.4f} corr={stats['corr']:.4f} "
        f"rmse={stats['rmse']:.4f}; months={len(proxy)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
