"""SPAN53 verification: the two donors that carry the panel to 1953-04.

Operational, not a test (network + FRED_API_KEY): the ust_10y GS10 splice on
real data, and the pegged-era fx parity index pinned to real DTWEXM. Writes
``docs/data/SPAN53-REPORT.md``. Store untouched.

Run:  uv run python scripts/span53_report.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "docs" / "data" / "SPAN53-REPORT.md"


def _load_env() -> None:
    if os.environ.get("FRED_API_KEY"):
        return
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("FRED_API_KEY=") and "=" in line:
                os.environ["FRED_API_KEY"] = line.split("=", 1)[1].strip()


def main() -> int:
    _load_env()
    if not os.environ.get("FRED_API_KEY"):
        print("FRED_API_KEY not set (checked env and .env)")
        return 1

    import pandas as pd

    from ah.data import fx_parity as fp
    from ah.data import ust10y_extend as tx
    from ah.data.connectors.fred import FredConnector
    from ah.data.manifest import load_requirements

    reqs = load_requirements()
    conn = FredConnector()
    frames: dict[str, pd.DataFrame] = {}
    for sid in ("fred.DGS10", "fred.GS10", "fred.DTWEXM"):
        req = reqs[sid]
        frames[sid] = conn.parse(conn.fetch(req), req)
        print(f"{sid}: {len(frames[sid])} obs")

    stats = tx.overlap_stats(frames["fred.DGS10"], frames["fred.GS10"])
    yext = tx.extend_ust10y(frames["fred.DGS10"], frames["fred.GS10"])
    yproxy = yext.frame.loc[yext.frame["is_proxy"]]

    fext = fp.extend_fx(frames["fred.DTWEXM"])
    fproxy = fext.frame.loc[fext.frame["is_proxy"]]
    steps = fproxy.set_index("date")["value"].pct_change().dropna()
    n_steps = int((steps.abs() > 1e-9).sum())

    lines = [
        "# SPAN53 — the two donors carrying the panel to 1953-04, verified",
        "",
        "*Generated by `scripts/span53_report.py`. Owner ruling 2026-08-09: the",
        "span-53 target. Nothing consumes either series until ratification.*",
        "",
        "## ust_10y: the GS10 splice (identity-class)",
        "",
        f"- Overlap {int(stats['n_obs'])} months: a = {stats['a']:+.4f}, "
        f"b = {stats['b']:.4f}, RMSE {stats['rmse']:.4f} pct, corr {stats['corr']:.5f} —",
        "  the near-identity the construction predicts (GS10 IS the monthly-average",
        "  ancestor of DGS10).",
        f"- {len(yproxy)} proxy months, {yproxy['date'].min().date()} .. "
        f"{yproxy['date'].max().date()}, rule `{tx.UST10Y_RULE.rule_id}`.",
        "",
        "## fx_usd: the pegged-era parity index",
        "",
        f"- {len(fproxy)} proxy months, {fproxy['date'].min().date()} .. "
        f"{fproxy['date'].max().date()}, rule `{fp.FX_PARITY_RULE.rule_id}`;",
        f"  junction scale {fext.junction_scale:.4f} (single-point level pin to",
        "  DTWEXM's first observation — no overlap exists by construction).",
        f"- The era's information is the steps: {n_steps} non-flat months out of",
        f"  {len(steps)}, the largest being the Smithsonian realignment "
        f"({steps.abs().idxmax().date()}, {float(steps.loc[steps.abs().idxmax()]):+.1%}).",
        "- Near-zero variance elsewhere is the pegged system's TRUE value, not",
        "  missing data. Consumers computing correlations over pegged-era blocks",
        "  need degenerate-variance guards — named as a ratification work item.",
        "",
        "## Caveats",
        "",
        "- Equal weights over six pegged majors are a documented choice; Canada is",
        "  excluded (floated 1950-62) and disclosed. The 1971-08..11 interregnum",
        "  is carried at prior parities, disclosed.",
        "- With these two verified, every factor in the active blocks reaches",
        "  1953-04 or earlier (policy_rate 1953-04..1954-06 rides the registered",
        "  fedfunds_pre1954 splice at ratification). The 1953-04 span is 813",
        "  months against the sealed 372.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    print(
        f"ust10y: corr={stats['corr']:.5f} rmse={stats['rmse']:.4f}; "
        f"fx: {len(fproxy)}m, {n_steps} steps, junction={fext.junction_scale:.4f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
