"""UST2YEXT verification: the curve-interpolated 2y extension on real data.

Operational, not a test (network + FRED_API_KEY): fetches DGS2, GS1 and GS3
through the registered FRED connector, fits the interpolation weights on the
1976+ overlap, and writes ``docs/data/UST2YEXT-REPORT.md``. The vintage
store is untouched.

Run:  uv run python scripts/ust2yext_overlap_report.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "docs" / "data" / "UST2YEXT-REPORT.md"

EPISODES = (
    ("1957-58 recession", "1957-01", "1958-12"),
    ("1966 credit crunch", "1966-01", "1966-12"),
    ("1969-70 tightening", "1969-01", "1970-12"),
    ("1973-74 oil shock", "1973-01", "1974-12"),
)


def _load_env() -> None:
    if os.environ.get("FRED_API_KEY"):
        return
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("FRED_API_KEY=") and "=" in line:
                os.environ["FRED_API_KEY"] = line.split("=", 1)[1].strip()


def main() -> int:
    _load_env()
    if not os.environ.get("FRED_API_KEY"):
        print("FRED_API_KEY not set (checked env and .env)")
        return 1

    import pandas as pd

    from ah.data import ust2y_extend as ux
    from ah.data.connectors.fred import FredConnector
    from ah.data.manifest import load_requirements

    reqs = load_requirements()
    conn = FredConnector()
    frames: dict[str, pd.DataFrame] = {}
    for sid in ("fred.DGS2", "fred.GS1", "fred.GS3"):
        req = reqs[sid]
        frames[sid] = conn.parse(conn.fetch(req), req)
        print(
            f"{sid}: {len(frames[sid])} obs, "
            f"{frames[sid]['date'].min().date()}..{frames[sid]['date'].max().date()}"
        )

    stats = ux.overlap_stats(frames["fred.DGS2"], frames["fred.GS1"], frames["fred.GS3"])
    ext = ux.extend_ust2y(frames["fred.DGS2"], frames["fred.GS1"], frames["fred.GS3"])
    proxy = ext.frame.loc[ext.frame["is_proxy"]]
    series = ext.frame.set_index("date")["value"]

    def _episode(lo: str, hi: str) -> str:
        w = series.loc[lo:hi]
        if len(w) == 0:
            return "no data"
        return f"peak {w.max():.2f} ({w.idxmax().date()}), mean {w.mean():.2f}"

    lines = [
        "# UST2YEXT — ust_2y extended to 1953 by curve interpolation, verified on real data",
        "",
        "*Generated by `scripts/ust2yext_overlap_report.py` (live FRED fetch; store",
        "untouched). Owner rulings U1-U3 in",
        "`docs/superpowers/specs/2026-08-09-ust2yext-decisions.md`; rule",
        f"`{ux.UST2Y_RULE.rule_id}`. Nothing consumes this series until the owner",
        "ratifies the span amendment.*",
        "",
        "## The fit (two-donor interpolation, 1976+ overlap)",
        "",
        "| quantity | value |",
        "|---|---|",
        f"| overlap months (n) | {int(stats['n_obs'])} |",
        f"| a (intercept, pct) | {stats['a']:.4f} |",
        f"| b1 (GS1 weight) | {stats['b1']:.4f} |",
        f"| b2 (GS3 weight) | {stats['b2']:.4f} |",
        f"| RMSE (pct points) | {stats['rmse']:.4f} |",
        f"| correlation | {stats['corr']:.4f} |",
        "",
        "## The extension",
        "",
        f"- **{len(proxy)}** proxy months "
        f"({proxy['date'].min().date()} .. {proxy['date'].max().date()}), all",
        f"  `is_proxy=True` under `{ux.UST2Y_RULE.rule_id}`; observed months",
        "  untouched (tested offline).",
        "",
        "## Episodes, as the extended series tells them",
        "",
    ]
    for name, lo, hi in EPISODES:
        lines.append(f"- **{name}**: {_episode(lo, hi)}")
    lines += [
        "",
        "## Caveats, stated before anyone asks",
        "",
        "- This is interpolation between OBSERVED points either side of the 2y",
        "  maturity on the same curve — the mildest recreation in the extension",
        "  family — but the fitted weights are 1976+ weights applied to a 1950s-60s",
        "  curve; the residual on the overlap is the honest measure of that risk.",
        "- The span consequence: with all four extensions verified, the binding",
        "  factor is now `fx_usd` (1973-01) — the Bretton Woods wall. The span",
        "  draft's addendum tracks the chain.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    print(
        f"fit: a={stats['a']:.4f} b1={stats['b1']:.4f} b2={stats['b2']:.4f} "
        f"corr={stats['corr']:.4f} rmse={stats['rmse']:.4f}; months={len(proxy)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
