"""Stage-1 overlap verification for the VXO->VIX extension (WP-DATA-VOLEXT).

Operational, not a test (network + FRED_API_KEY): fetches ``fred.VIX`` and
``fred.VXO`` through the real FRED connector, fits
``ah.data.vol_extend.VXO_RULE``'s log-log link on the 1990+ overlap, and
writes ``docs/data/VOLEXT-STAGE1.md`` -- the "verify the overlap fit before
accepting it" evidence the task requires, and the report the proposed
``block_draw_span`` amendment cites.

Deliberately reads nothing from and writes nothing to the vintage store:
the store path is ``ah data refresh --live``, and when a vintage is
QUARANTINED by QC the quarantine is respected, not bypassed. This script's
fetch is a verification read, exactly like ``scripts/download_data.py``'s
summary role.

Run:  uv run python scripts/volext_overlap_report.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUT = ROOT / "docs" / "data" / "VOLEXT-STAGE1.md"


def _load_env() -> None:
    if os.environ.get("FRED_API_KEY"):
        return
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("FRED_API_KEY=") and "=" in line:
                os.environ["FRED_API_KEY"] = line.split("=", 1)[1].strip()


def main() -> int:
    _load_env()
    if not os.environ.get("FRED_API_KEY"):
        print("FRED_API_KEY not set (checked env and .env)")
        return 1

    import pandas as pd

    from ah.data import vol_extend as vx
    from ah.data.connectors.fred import FredConnector
    from ah.data.manifest import load_requirements

    reqs = load_requirements()
    conn = FredConnector()
    frames: dict[str, pd.DataFrame] = {}
    for sid in ("fred.VIX", "fred.VXO"):
        req = reqs[sid]
        frames[sid] = conn.parse(conn.fetch(req), req)
        print(
            f"{sid}: {len(frames[sid])} monthly obs, {frames[sid]['date'].min().date()}..{frames[sid]['date'].max().date()}"
        )

    stats = vx.overlap_stats(frames["fred.VIX"], frames["fred.VXO"])
    ext = vx.extend_equity_vol(frames["fred.VIX"], frames["fred.VXO"])
    proxy = ext.frame.loc[ext.frame["is_proxy"]]

    oct87 = proxy.loc[proxy["date"].dt.strftime("%Y-%m") == "1987-10", "value"]
    oct87_vixeq = float(oct87.iloc[0]) if len(oct87) else float("nan")
    vxo = frames["fred.VXO"].set_index("date")["value"]
    oct87_rows = vxo[vxo.index.strftime("%Y-%m") == "1987-10"]
    oct87_vxo = float(oct87_rows.iloc[0]) if len(oct87_rows) else float("nan")

    lines = [
        "# VOLEXT Stage 1 — the VXO overlap fit, verified on real data",
        "",
        "*Generated by `scripts/volext_overlap_report.py` (live FRED fetch through the",
        "registered connector; the vintage store is untouched). This is the overlap",
        "scrutiny `Instructions/TASK-vol-backcast-claude-code.md` requires before the",
        "extension is accepted, and the evidence the proposed amendment",
        "`governance/proposed/PROPOSED-AM-block-draw-span-1986.md` cites. Rule:",
        f"`{vx.VXO_RULE.rule_id}` — log VIX = a + b·log VXO, fitted on the 1990+ overlap.*",
        "",
        "## The fit",
        "",
        "| quantity | value |",
        "|---|---|",
        f"| overlap months (n) | {int(stats['n_obs'])} |",
        f"| a (intercept, log) | {stats['a']:.6f} |",
        f"| b (slope, log-log) | {stats['b']:.6f} |",
        f"| RMSE, log space | {stats['rmse_log']:.4f} |",
        f"| RMSE, level (vol points) | {stats['rmse_level']:.3f} |",
        f"| correlation, log levels | {stats['corr_log']:.4f} |",
        "",
        "## The extension",
        "",
        f"- Proxy months written: **{len(proxy)}** "
        f"({proxy['date'].min().date()} .. {proxy['date'].max().date()}), all "
        "`is_proxy=True`; no observed month touched (invariant is tested offline).",
        f"- October 1987: observed VXO month-end **{oct87_vxo:.1f}** maps to a "
        f"VIX-equivalent of **{oct87_vixeq:.1f}** — the number the stage-2 backcast's "
        "held-out check is scored against.",
        "",
        "## Caveats, stated before anyone asks",
        "",
        "- VXO is ATM S&P **100** implied vol; the link to VIX (S&P 500) is a fitted",
        "  transform, not an identity. The fit above is the whole of the evidence.",
        "- 1986-89 proxy months are observation-derived but still proxies: any",
        "  statistic over the extended span must disclose the proxy share.",
        "- Nothing consumes this series until the owner ratifies the proposed",
        "  amendment. `block_draw_span` is unchanged; `funding_spread` (TED,",
        "  1986-01) binds at 1986 regardless.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    print(
        f"fit: a={stats['a']:.4f} b={stats['b']:.4f} corr_log={stats['corr_log']:.4f} rmse_log={stats['rmse_log']:.4f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
